apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: solution-snow

namePrefix: solution-snow-

patches:
- path: patches/route.yaml
  target:
    group: route.openshift.io
    version: v1
    kind: Route
- path: patches/vault-role.yaml
  target:
    kind: Deployment

# -- App specific --

replicas:
- name: solution-snow-testid
  count: 1

images:
- name: default
  newName: oyriimagerepo.no/testid
  digest: sha256:088313f64d6779f2ccce2d1b3389b31f01de42698fa99a2213af01f849ef4591

configMapGenerator:
- name: application-config
  files:
  - configs/config.yaml
- name: container-envs
  envs:
  - configs/container.env
