apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: solution-snow

namePrefix: solution-snow-

patches:
- path: patches/route.yaml
  target:
    group: route.openshift.io
    version: v1
    kind: Route
- path: patches/vault-role.yaml
  target:
    kind: Deployment

# -- App specific --

replicas:
- name: solution-snow-testid
  count: 1

images:
- op: replace
  path: /spec/template/spec/containers/0/image
  value: oyri.io/testid:2022-02-22-0924-72b05254@sha256:d46cad4eb57aba2f60b184fc7506ec5d212196193d1b0d178d8d828a5aca4269

configMapGenerator:
- name: application-config
  files:
  - configs/config.yaml
- name: container-envs
  envs:
  - configs/container.env
