# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deliver code to config repo

on:
  push:
    branches: [ dd ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APPLICATION: testing-actions
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> $GITHUB_ENV
      - run: echo "branch ${{github.ref_name}} -BASE_REF ${{ github.base_ref }} -REF ${GITHUB_REF} -REF-hash ${GITHUB_REF##*/} -REF-refs/heads ${GITHUB_REF#refs/heads/}"      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"      
      - name: 'update cd'
        uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4 # pin@v1.1.3
        with:
          token: ${{ secrets.OYRI_GITHUB_REPO_TOKEN }}
          event-type: update-oyri-version
          repository: 'oyri/testing-github-action-config'
          client-payload: '{"application": "${{env.APPLICATION}}","version":"${{env.IMAGETAG}}","issue":"TODO"}'
