# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APPLICATION: testing-actions
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: 'update cd'
        uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4 # pin@v1.1.3
        with:
          token: ${{ secrets.EID_BUILD_PAT }}
          event-type: update-oyri-version
          repository: 'oyri/testing-github-actions'
          client-payload: '{"application": "${{env.APPLICATION}}","version":"${{env.IMAGETAG}}"}'
