name: set params
on:
  workflow_dispatch:
jobs:
  variables-save:
    name: testing
    runs-on: "ubuntu-latest"
    steps:
     - name: print filename
       id: print
       run: |
        touch randi.txt
        echo "FILENAME=$(ls)" >> $GITHUB_OUTPUT
     - name: echo filename ${{ steps.print.outputs.FILENAME }}
       run: file ${{ steps.print.outputs.FILENAME }}
        
