name: Sende author to repo
on:
  repository_dispatch:
    types: [update-version]
env:
  IMAGE-NAME: ${{ github.event.client_payload.image-name }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> "$GITHUB_ENV"
      - id: echo-image-name
        run: echo imagename ${{env.IMAGE-NAME}}
      - id: echo-author-obj
        run: echo ${{ github.event.client_payload.author }}
      - id: author-print
        run: echo "jira ${{ github.event.client_payload.jira-id }} name ${{ github.event.client_payload.author.name }} email ${{ github.event.client_payload.author.email }} username ${{ github.event.client_payload.author.username }}"
