name: Testing replace image version in config file
on:
  workflow_dispatch:
   inputs:
      image-version:
        description: 'New image version'
        required: true
      image-name:
        description: 'Image to update'
        required: true        
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log input parameters
        run: echo "Image name [${{ github.event.inputs.image-name }}] and version [${{ github.event.inputs.image-version }}]."
      - name: Find and replace image version in solution-fjord
        uses: jacobtomlinson/gha-find-replace@v2
        id: update-version-solution-fjord
        with:
          find: "oyriimagerepo.no/${{ github.event.inputs.image-name }}:\\d{4}-\\d{2}-\\d{2}-\\d{4}-[\\w]+"
          replace: "oyriimagerepo.no/${{ github.event.inputs.image-name }}:${{ github.event.inputs.image-version }}"
          include: "solution-fjord/*.yaml"
          regex: true
      - name: Log version update in solution-fjord
        run: echo "Version is updated in ${{ steps.update-version-solution-fjord.outputs.modifiedFiles }} files."
      - name: Find and replace image version in solution-mountain
        uses: jacobtomlinson/gha-find-replace@v2
        id: update-version-solution-mountain
        with:
          find: "oyriimagerepo.no/${{ github.event.inputs.image-name }}:\\d{4}-\\d{2}-\\d{2}-\\d{4}-[\\w]+"
          replace: "oyriimagerepo.no/${{ github.event.inputs.image-name }}:${{ github.event.inputs.image-version }}"
          include: "solution-mountain/*.yaml"
          regex: true
      - name: Log version update in solution-mountain
        run: echo "Version is updated in ${{ steps.update-version-solution-mountain.outputs.modifiedFiles }} files."   
      - name: create pull request
        uses: peter-evans/create-pull-request@5e9d0ee9ea5ccf865a52a571cba827e4b52a1aff # pin@v3.8.0
        with:
          commit-message: "updating version of ${{ github.event.inputs.image-name }} to ${{ github.event.inputs.image-version }}"
          branch: ${{ github.event.inputs.image-name }}-version-update
          delete-branch: true
          branch-suffix: random
          title: "updating version of ${{ github.event.inputs.image-name }} to ${{ github.event.inputs.image-version }}"
          body: "Automated pull-request"
