name: Sende parameters between jobs
on:
  workflow_dispatch:
   inputs:
      image-name:
        description: 'Image to update'
        required: true
        type: string
      author:
        description: 'Author as JSON'
        required: true
        type: string        
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      IMAGE-NAME:  toJSON(${{ inputs.author}})
      AUTHOR: ${{ inputs.image-name }}
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.imagetag }}
      output2: ${{ steps.step2.outputs.imagedigest }}
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> "$GITHUB_ENV"
      - name: Set image digest
        run: echo "IMAGE_DIGEST='00001111abc'" >> "$GITHUB_ENV"        
      - id: step1
        run: echo "::set-output name=imagetag::${{env.IMAGETAG}}"
      - id: step2
        run: echo "::set-output name=imagedigest::${{env.IMAGE_DIGEST}}"
      - id: echo-image-name
        run: echo imagename ${{env.IMAGE-NAME}}
      - id: author-print
        run: echo "name ${{env.IMAGE-NAME.name}} email ${{env.IMAGE-NAME.email}} username ${{env.IMAGE-NAME.username}}"
  version-update1:
    runs-on: ubuntu-latest
    env:
      IMAGE-NAME:  ${{ inputs.image-name }}    
    needs: job1
    steps:
      - run: echo version-update1 ${{needs.job1.outputs.output1}} - ${{needs.job1.outputs.output2}} - ${{env.IMAGE-NAME}}
  version-update2:
    runs-on: ubuntu-latest
    env:
      IMAGE-NAME:  ${{ inputs.image-name }}    
    needs: job1
    steps:
      - run: echo version-update2 ${{needs.job1.outputs.output1}} - ${{needs.job1.outputs.output2}} - ${{env.IMAGE-NAME}}      
